### PR TITLE
ARROW-107 Test against Python 3.11 beta

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Review by ShaneHarvey — APPROVED** [review]

**Comment by blink1073** [comment]
Looks like we need libarrow to build against since there are no Python 3.11 wheels for PyArrow.

**Comment by ShaneHarvey** [comment]
Ah, let's close this PR and mark the jira ticket blocked?

**Comment by blink1073** [comment]
> Ah, let's close this PR and mark the jira ticket blocked?

That or we could switch to using a conda environment like we do in the docs build and depend on libarrow.

**Comment by ShaneHarvey** [comment]
Sounds like too much effort. We also need to wait for Cython numpy and pandas to support 3.11 too.

**Comment by blink1073** [comment]
Good point, backlogging.

**Pull request closed without merging**
